#.air.toml


# 监听目录
root = "."
tmp_dir = "tmp"
# 要忽略的目录或文件
[ignore]
files = ["vendor","tmp","logs",".git",".vscode"]


#运行的命令 ,go run main.go 或go build + 二进制文件
[build]
cmd = "go build -o ./tmp/main ."
bin ="./tmp/main"
delay  = 1000

[server]
addr = "0.0.0.0:88"

[log]
time = true
